name              "nlc"
maintainer        "Ryan Solida"
maintainer_email  "ryan@mozay.com"
license           "MIT"
description       "Sets up necessary steps for running the NLC process"
version           "1.0.0"
